services:
  depot:
    image: ghcr.io/david-stefan-hermann/depot:latest
    restart: unless-stopped
    volumes:
      - /mnt/tank/applications/nextcloud-user-data/vault-boy/files:/nextcloud-data:ro
      - depot-scratch:/scratch
    env_file:
      - .env

volumes:
  depot-scratch:
